fix: CI

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -62,15 +62,15 @@ jobs:
             --baseURL "${{ steps.pages.outputs.base_url }}"
         continue-on-error: false
       - name: Verify build
-          run: |
-            if [ ! -d "public" ]; then
-              echo "Hugo build failed - public directory not found"
-              exit 1
-            else
-              echo "Hugo build succeeded - public directory found"
-              echo "Listing files in public directory:"
-              find public
-            fi
+        run: |
+          if [ ! -d "public" ]; then
+            echo "Hugo build failed - public directory not found"
+            exit 1
+          else
+            echo "Hugo build succeeded - public directory found"
+            echo "Listing files in public directory:"
+            find public
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
